const trips = [
    // --- צפון ---
    {
        id: "trip_1",
        name: "שמורת טבע תל דן",
        shortDescription: "הליכה רומנטית ומוצלת לצד פלגי מים צלולים וצמחייה עשירה.",
        region: "צפון",
        routeType: "מעגלי",
        lengthCategory: "קצר",
        durationText: "כשעה עד שעתיים",
        durationCategory: "2-3 שעות",
        difficulty: "קל",
        style: ["טבע", "מים", "רומנטי"],
        hasFoodOption: true,
        elevationDetail: "מסלול מישורי ברובו, מונגש בחלקו הגדול.",
        driveDistance: "נסיעה צפונה לאצבע הגליל.",
        startPoint: "קופות השמורה תל דן",
        endPoint: "קופות השמורה תל דן",
        highlights: ["שכשוך רגליים בבריכת השכשוך", "הליכה בתוך 'יער המכשפות'", "שרידי עיר קדומה"],
        foodRecommendations: "מומלץ לשלב ארוחת צהריים במסעדת דגים באזור או לעצור בקריית שמונה.",
        whatToBring: "נעלי הליכה נוחות, כובע, מים וסנדלים לשכשוך.",
        seasonSuitability: "מושלם באביב ובקיץ החם.",
        timeSuitability: ["בוקר", "צהריים"],
        mapsLink: "https://goo.gl/maps/d8bJ1wzL3jFq6E2X7",
        infoLink: "https://www.parks.org.il/reserve-park/tel-dan/"
    },
    {
        id: "trip_2",
        name: "מצפור כנרת (יער שוויץ)",
        shortDescription: "תצפיות עוצרות נשימה לכנרת ולגולן ממרומי יער שוויץ.",
        region: "צפון",
        routeType: "קצר",
        lengthCategory: "קצר",
        durationText: "כשעה (ללא הפיקניק)",
        durationCategory: "2-3 שעות",
        difficulty: "קל",
        style: ["נוף", "רומנטי", "שקיעה", "טבע"],
        hasFoodOption: true,
        elevationDetail: "נקודות תצפית קרובות לחניה, כמעט ללא מאמץ.",
        driveDistance: "רבע שעה מטבריה.",
        startPoint: "חניון מצפור כנרת",
        endPoint: "חניון מצפור כנרת",
        highlights: ["נוף פנורמי של הכנרת", "פינות ישיבה מושלמות לקפה/פקניק", "צמחיית יער צפופה"],
        foodRecommendations: "הביאו אתכם מצרכים לפיקניק שקיעה, או סעו למסעדות בטבריה.",
        whatToBring: "מחצלת, סלסלת פיקניק, פק\"ל קפה וביגוד חם לערב.",
        seasonSuitability: "מתאים לכל השנה, במיוחד בסתיו ובאביב.",
        timeSuitability: ["שקיעה"],
        mapsLink: "https://goo.gl/maps/bTj2K3n2R8R5p8C98",
        infoLink: "https://www.kkl.org.il/forestsearch/switzerland_forest.aspx"
    },
    {
        id: "trip_3",
        name: "נחל שניר (חצבני)",
        shortDescription: "מסלול הליכה מרענן בתוך המים, מושלם ליום חם.",
        region: "צפון",
        routeType: "מעגלי",
        lengthCategory: "ארוך",
        durationText: "כ-3 שעות",
        durationCategory: "חצי יום",
        difficulty: "בינוני",
        style: ["טבע", "מים"],
        hasFoodOption: true,
        elevationDetail: "הליכה בתוך תוואי הנחל על חלוקי נחל, דורש יציבות.",
        driveDistance: "קרוב לקיבוץ הגושרים.",
        startPoint: "חניון שמורת נחל שניר",
        endPoint: "חניון שמורת נחל שניר",
        highlights: ["הליכה במים זורמים", "מפלונים קטנים", "צל כמעט לאורך כל הדרך"],
        foodRecommendations: "מסעדות מעולות במתחם גן הצפון הקרוב.",
        whatToBring: "נעליים להליכה במים (חובה), בגדי ים, מגבת.",
        seasonSuitability: "קיץ ואביב. סגור בימי שיטפון.",
        timeSuitability: ["בוקר", "צהריים"],
        mapsLink: "https://goo.gl/maps/4zWkXwZ2jK8X1qK6A",
        infoLink: "https://www.parks.org.il/reserve-park/nahal-snir/"
    },
    {
        id: "trip_4",
        name: "שביל הפסגה בהר מירון",
        shortDescription: "מסלול מעגלי קליל בשיא הגובה, עם תצפיות פנורמיות לגליל.",
        region: "צפון",
        routeType: "מעגלי",
        lengthCategory: "קצר",
        durationText: "כ-1.5 שעות",
        durationCategory: "2-3 שעות",
        difficulty: "קל",
        style: ["טבע", "נוף"],
        hasFoodOption: true,
        elevationDetail: "עליות וירידות מתונות, שביל מסודר ונוח.",
        driveDistance: "כ-20 דקות מצפת.",
        startPoint: "חניון הפסגה הר מירון",
        endPoint: "חניון הפסגה הר מירון",
        highlights: ["תצפיות לכל כיווני הגליל והגולן", "אוויר הרים צלול גם בקיץ", "חורש ים תיכוני סבוך"],
        foodRecommendations: "שלבו ארוחה באחת ממסעדות צפת או יקב באזור דלתון.",
        whatToBring: "נעלי הליכה, מים וז'קט (תמיד קריר שם למעלה).",
        seasonSuitability: "כל השנה. יפהפה בעונות המעבר.",
        timeSuitability: ["בוקר", "אחה\"צ"],
        mapsLink: "https://goo.gl/maps/x6jV7vN3K8M2wK1v5",
        infoLink: "https://www.parks.org.il/reserve-park/mount-meron/"
    },
    {
        id: "trip_5",
        name: "אגמון החולה - רכיבה זוגית",
        shortDescription: "השכרת אופניים זוגיים ורכיבה נינוחה סביב האגם בין הציפורים.",
        region: "צפון",
        routeType: "מעגלי",
        lengthCategory: "ארוך",
        durationText: "כ-3 שעות",
        durationCategory: "חצי יום",
        difficulty: "קל",
        style: ["טבע", "רומנטי", "נוף"],
        hasFoodOption: true,
        elevationDetail: "שטוח לחלוטין, שבילים סלולים.",
        driveDistance: "עמק החולה.",
        startPoint: "מרכז המבקרים אגמון החולה",
        endPoint: "מרכז המבקרים אגמון החולה",
        highlights: ["תצפית על להקות ציפורים", "מצפורים צפים על המים", "שקט ושלווה מול הגולן"],
        foodRecommendations: "במקום יש בית קפה קליל. אפשר לאכול בראש פינה בסיום.",
        whatToBring: "משקפת (מומלץ), כובע, מצלמה.",
        seasonSuitability: "מושלם בעונות הנדידה (סתיו ואביב).",
        timeSuitability: ["בוקר", "שקיעה"],
        mapsLink: "https://goo.gl/maps/c6jV7vN3K8M2wK1v6",
        infoLink: "https://agamon-hula.co.il/"
    },
    {
        id: "trip_6",
        name: "עין חרדלית ונחל כזיב",
        shortDescription: "קפיצה למים צלולים באחת הפינות הקסומות בגליל המערבי.",
        region: "צפון",
        routeType: "קצר",
        lengthCategory: "קצר",
        durationText: "1-2 שעות",
        durationCategory: "2-3 שעות",
        difficulty: "קל",
        style: ["מים", "טבע", "רומנטי"],
        hasFoodOption: true,
        elevationDetail: "מישורי, הליכה קצרה מהחניה למים.",
        driveDistance: "ליד היישוב מנות/עבדון.",
        startPoint: "חניון עין חרדלית",
        endPoint: "חניון עין חרדלית",
        highlights: ["מים רדודים וצלולים", "עצי דולב ענקיים", "שקט גלילי"],
        foodRecommendations: "מעולה לפיקניק. לחלופין, מסעדות בנהריה או ירכא בקרבת מקום.",
        whatToBring: "בגדי ים, סנדלי מים, מחצלת.",
        seasonSuitability: "קיץ, אביב וסתיו חם.",
        timeSuitability: ["בוקר", "צהריים"],
        mapsLink: "https://goo.gl/maps/8jV7vN3K8M2wK1v7",
        infoLink: "https://www.parks.org.il/"
    },

    // --- מרכז ---
    {
        id: "trip_7",
        name: "גן לאומי אפולוניה",
        shortDescription: "שרידי מבצר צלבני יפהפה הניצב על צוק מעל הים התיכון.",
        region: "מרכז",
        routeType: "מעגלי",
        lengthCategory: "קצר",
        durationText: "כשעה",
        durationCategory: "2-3 שעות",
        difficulty: "קל",
        style: ["נוף", "רומנטי", "שקיעה"],
        hasFoodOption: true,
        elevationDetail: "שביל מוסדר ומישורי בעיקרו עם מעט מדרגות למבצר.",
        driveDistance: "מרחק קצר מהרצליה.",
        startPoint: "קופות גן לאומי אפולוניה",
        endPoint: "קופות גן לאומי אפולוניה",
        highlights: ["תצפית מרהיבה לים", "חורבות המבצר הצלבני", "בריזה ים תיכונית"],
        foodRecommendations: "מומלץ לשלב ארוחת ערב במסעדות המרינה של הרצליה לאחר מכן.",
        whatToBring: "מצלמה, נעליים נוחות, וז'קט קל אם באים בשקיעה.",
        seasonSuitability: "מושלם בכל עונות השנה.",
        timeSuitability: ["שקיעה", "אחה\"צ"],
        mapsLink: "https://goo.gl/maps/c6jV7vN3K8M2wK1v8",
        infoLink: "https://www.parks.org.il/reserve-park/apollonia/"
    },
    {
        id: "trip_8",
        name: "נחל אלכסנדר ופארק צבי המים",
        shortDescription: "טיול רגוע לאורך הנחל, צפייה בצבים רכים רחבי שריון.",
        region: "מרכז",
        routeType: "קצר",
        lengthCategory: "קצר",
        durationText: "כשעה - שעתיים",
        durationCategory: "2-3 שעות",
        difficulty: "קל",
        style: ["טבע", "רומנטי", "מים"],
        hasFoodOption: true,
        elevationDetail: "מישורי, מונגש ברובו (שבילים סלולים).",
        driveDistance: "עמק חפר, קרוב לכפר ויתקין.",
        startPoint: "גשר הצבים",
        endPoint: "שפך נחל אלכסנדר (ניתן לעשות קווי או לחזור)",
        highlights: ["צפייה בצבים הרכים", "שבילי הליכה ירוקים", "חוליות בשפך לים"],
        foodRecommendations: "אזור תעשייה עמק חפר מציע עגלות קפה ובתי קפה מצוינים.",
        whatToBring: "כובע, מים, אופניים (אם יש).",
        seasonSuitability: "סתיו, חורף, אביב.",
        timeSuitability: ["בוקר", "אחה\"צ"],
        mapsLink: "https://goo.gl/maps/c6jV7vN3K8M2wK1v9",
        infoLink: "https://www.parks.org.il/"
    },
    {
        id: "trip_9",
        name: "יער בן שמן - מצפה מודיעין",
        shortDescription: "מרחבים ירוקים, שבילים מוצלים ופינות חמד במרכז הארץ.",
        region: "מרכז",
        routeType: "מעגלי",
        lengthCategory: "קצר",
        durationText: "כשעה הליכה (או נסיעה ביער)",
        durationCategory: "2-3 שעות",
        difficulty: "קל",
        style: ["טבע", "נוף", "רומנטי"],
        hasFoodOption: true,
        elevationDetail: "עליות מתונות, מגוון שבילים.",
        driveDistance: "ליד מודיעין וכביש 1.",
        startPoint: "מצפה מודיעין",
        endPoint: "מצפה מודיעין",
        highlights: ["תצפית יפה על האזור", "שבילי אופניים", "מרבדי פריחה (בחורף/אביב)"],
        foodRecommendations: "הכי קלאסי - פיקניק או פק\"ל קפה. אחרת, מסעדות במודיעין.",
        whatToBring: "מחצלת, קפה, נשנושים.",
        seasonSuitability: "חורף ואביב במיוחד.",
        timeSuitability: ["בוקר", "אחה\"צ"],
        mapsLink: "https://goo.gl/maps/c6jV7vN3K8M2wK1v0",
        infoLink: "https://www.kkl.org.il/forestsearch/ben_shemen_forest.aspx"
    },
    {
        id: "trip_10",
        name: "שמורת חוף השרון",
        shortDescription: "הליכה רומנטית על רכס כורכר המשקיף על הים הפתוח.",
        region: "מרכז",
        routeType: "מעגלי",
        lengthCategory: "קצר",
        durationText: "1.5 שעות",
        durationCategory: "2-3 שעות",
        difficulty: "קל",
        style: ["נוף", "רומנטי", "שקיעה", "טבע"],
        hasFoodOption: true,
        elevationDetail: "הליכה חולית קלה, מישורי בעיקרו.",
        driveDistance: "סמוך לקיבוץ שפיים.",
        startPoint: "חניון שמורת חוף השרון",
        endPoint: "חניון שמורת חוף השרון",
        highlights: ["נוף ים פנורמי", "פריחה עונתית יפה", "תצפיות שקיעה מדהימות"],
        foodRecommendations: "קפצו למתחם געש/שפיים הקרוב להמון אופציות קולינריות.",
        whatToBring: "נעלי הליכה שמתאימות לחול, מים, ומצלמה.",
        seasonSuitability: "כל השנה. מדהים במיוחד בשקיעות של סתיו ואביב.",
        timeSuitability: ["שקיעה"],
        mapsLink: "https://goo.gl/maps/c6jV7vN3K8M2wK1v1",
        infoLink: "https://www.parks.org.il/"
    },
    {
        id: "trip_11",
        name: "יפו העתיקה ופארק המדרון",
        shortDescription: "שילוב של סמטאות היסטוריות, אמנות, והליכה על קו המים.",
        region: "מרכז",
        routeType: "מעגלי",
        lengthCategory: "ארוך",
        durationText: "2-3 שעות",
        durationCategory: "חצי יום",
        difficulty: "קל",
        style: ["קולינרי", "רומנטי", "נוף", "שקיעה"],
        hasFoodOption: true,
        elevationDetail: "סמטאות מרוצפות, מדרגות באזור העתיק. הפארק מישורי.",
        driveDistance: "תל אביב - יפו.",
        startPoint: "כיכר קדומים, יפו",
        endPoint: "נמל יפו",
        highlights: ["סמטאות המזלות", "גשר המשאלות", "מדרון יפו מול הים"],
        foodRecommendations: "אינסוף אפשרויות: מסעדות שף, מאפיות מסורתיות וברים בשוק הפשפשים.",
        whatToBring: "נעליים נוחות להליכה עירונית.",
        seasonSuitability: "כל השנה.",
        timeSuitability: ["אחה\"צ", "שקיעה"],
        mapsLink: "https://goo.gl/maps/c6jV7vN3K8M2wK1v2",
        infoLink: "https://www.oldjaffa.co.il/"
    },
    {
        id: "trip_12",
        name: "תל אפק (מבצר אנטיפטריס)",
        shortDescription: "אגם מלאכותי, מבצר עתיק ומרחבי דשא עצומים בלב גוש דן.",
        region: "מרכז",
        routeType: "מעגלי",
        lengthCategory: "קצר",
        durationText: "1-2 שעות",
        durationCategory: "2-3 שעות",
        difficulty: "קל",
        style: ["טבע", "מים", "רומנטי"],
        hasFoodOption: true,
        elevationDetail: "מישורי, מונגש ונוח מאוד להליכה.",
        driveDistance: "ליד ראש העין / פתח תקווה.",
        startPoint: "קופות תל אפק",
        endPoint: "קופות תל אפק",
        highlights: ["המבצר המרשים", "האגם והצמחייה מסביב", "מקורות נחל הירקון"],
        foodRecommendations: "מעולה לפיקניק זוגי מושקע על הדשא. או מסעדות בפתח תקווה.",
        whatToBring: "סלסלת פיקניק, מחצלת.",
        seasonSuitability: "סתיו, חורף (ירוק!), אביב.",
        timeSuitability: ["בוקר", "צהריים"],
        mapsLink: "https://goo.gl/maps/c6jV7vN3K8M2wK1v3",
        infoLink: "https://www.parks.org.il/reserve-park/yarkon-afek/"
    },

    // --- ירושלים והסביבה ---
    {
        id: "trip_13",
        name: "עין כרם והסמטאות",
        shortDescription: "כפר ציורי בתוך העיר, מלא באווירה רומנטית, כנסיות ובתי קפה.",
        region: "ירושלים והסביבה",
        routeType: "מעגלי",
        lengthCategory: "קצר",
        durationText: "כ-2 שעות",
        durationCategory: "חצי יום",
        difficulty: "קל",
        style: ["רומנטי", "קולינרי", "נוף"],
        hasFoodOption: true,
        elevationDetail: "שילוב של עליות וירידות תלולות בסמטאות (הררי).",
        driveDistance: "בתוך ירושלים (פאתי העיר).",
        startPoint: "מרכז הכפר (מעיין מרים)",
        endPoint: "מרכז הכפר",
        highlights: ["מעיין מרים", "תצפיות להרי ירושלים", "גלריות קטנות"],
        foodRecommendations: "מסעדות מעולות ממש בכפר (איטלקי, בתי קפה ציוריים).",
        whatToBring: "נעלי הליכה נוחות, לבוש צנוע (אם נכנסים לכנסיות).",
        seasonSuitability: "סתיו ואביב, וגם חורף לא גשום.",
        timeSuitability: ["בוקר", "אחה\"צ"],
        mapsLink: "https://goo.gl/maps/c6jV7vN3K8M2wK1v4",
        infoLink: "https://www.itraveljerusalem.com/he/neighborhood/ein-kerem/"
    },
    {
        id: "trip_14",
        name: "סטף - חקלאות קדומה",
        shortDescription: "טיול בין מעיינות ניקבה, טרסות חקלאיות ובוסתנים בהרי ירושלים.",
        region: "ירושלים והסביבה",
        routeType: "מעגלי",
        lengthCategory: "ארוך",
        durationText: "כ-2.5 שעות",
        durationCategory: "חצי יום",
        difficulty: "בינוני",
        style: ["טבע", "מים", "נוף"],
        hasFoodOption: true,
        elevationDetail: "ירידה מהחניה למעיינות, ועלייה תלולה חזרה לחניה העליונה.",
        driveDistance: "הרי ירושלים, ליד מבשרת ציון.",
        startPoint: "חניון הסטף העליון",
        endPoint: "חניון הסטף העליון",
        highlights: ["עין ביכורה ועין סטף (ניתן להליכה בניקבה חשוכה)", "טרסות ירוקות", "נוף ההרים"],
        foodRecommendations: "בית הקפה בסטף למעלה, או באבו גוש הסמוכה.",
        whatToBring: "פנס (לניקבה), סנדלי מים, נעלי הליכה טובות לעלייה.",
        seasonSuitability: "אביב (פריחת שקדיות) וסתיו.",
        timeSuitability: ["בוקר"],
        mapsLink: "https://goo.gl/maps/c6jV7vN3K8M2wK1v5",
        infoLink: "https://www.kkl.org.il/forestsearch/sataf.aspx"
    },
    {
        id: "trip_15",
        name: "נחל חלילים",
        shortDescription: "מסלול קצר ומקסים המשלב טבע ומערות שניתן לזחול בהן.",
        region: "ירושלים והסביבה",
        routeType: "קווי",
        lengthCategory: "ארוך",
        durationText: "2-3 שעות",
        durationCategory: "חצי יום",
        difficulty: "בינוני",
        style: ["טבע", "נוף"],
        hasFoodOption: true,
        elevationDetail: "ירידה מתונה מתמשכת (אם עושים אותו במורד הנחל).",
        driveDistance: "מבשרת ציון.",
        startPoint: "מבשרת ציון (רחוב השלום)",
        endPoint: "עמק הארזים",
        highlights: ["מערות חלילים המרתקות", "פריחה צפופה בחורף", "נוף הרי ירושלים"],
        foodRecommendations: "הצטיידו במאפים במבשרת ציון לפני תחילת המסלול.",
        whatToBring: "נעלי הליכה, מים (צריך רכב הקפצה או הליכה חזרה בעלייה).",
        seasonSuitability: "חורף ואביב.",
        timeSuitability: ["בוקר"],
        mapsLink: "https://goo.gl/maps/c6jV7vN3K8M2wK1v6",
        infoLink: "https://www.parks.org.il/"
    },
    {
        id: "trip_16",
        name: "פארק טדי ושדרות אלרוב (ממילא)",
        shortDescription: "טיול עירוני-רומנטי המשלב מזרקות, תרבות וקניות מול חומות העיר העתיקה.",
        region: "ירושלים והסביבה",
        routeType: "מעגלי",
        lengthCategory: "קצר",
        durationText: "1-2 שעות",
        durationCategory: "2-3 שעות",
        difficulty: "קל",
        style: ["רומנטי", "קולינרי", "שקיעה"],
        hasFoodOption: true,
        elevationDetail: "הליכה עירונית נינוחה ומונגשת.",
        driveDistance: "מרכז ירושלים.",
        startPoint: "שדרת ממילא",
        endPoint: "פארק טדי / מתחם התחנה",
        highlights: ["מזרקות המים של פארק טדי", "נוף מרהיב לחומות המוארות", "שדרת הקניות אלרוב"],
        foodRecommendations: "עשרות מסעדות ובתי קפה בממילא או במתחם התחנה.",
        whatToBring: "לבוש נוח, מצלמה, ז'קט (ירושלים קרירה בערב).",
        seasonSuitability: "כל השנה. מרהיב במיוחד בערב.",
        timeSuitability: ["שקיעה", "ערב"],
        mapsLink: "https://goo.gl/maps/c6jV7vN3K8M2wK1v7",
        infoLink: "https://www.itraveljerusalem.com/"
    },
    {
        id: "trip_17",
        name: "יער הקדושים ומערת בני ברית",
        shortDescription: "נסיעה ציורית בתוך יער קסום, עצירה בפינות ירוקות לפיקניק אינטימי.",
        region: "ירושלים והסביבה",
        routeType: "קצר",
        lengthCategory: "קצר",
        durationText: "כשעה הליכה קלה",
        durationCategory: "2-3 שעות",
        difficulty: "קל",
        style: ["טבע", "רומנטי", "נוף"],
        hasFoodOption: true,
        elevationDetail: "השבילים ליד החניונים שטוחים ונוחים.",
        driveDistance: "סמוך לצומת אשתאול / שמשון.",
        startPoint: "חניון מערת בני ברית",
        endPoint: "חניון מערת בני ברית",
        highlights: ["יער ירוק וצפוף", "מערת בני ברית", "פינות פיקניק שקטות לאורך נחל כסלון"],
        foodRecommendations: "אידיאלי לפיקניק. ניתן לקפוץ למסעדות עין כרם או אבו גוש לפני/אחרי.",
        whatToBring: "ערכת קפה, אוכל לפיקניק, מחצלת.",
        seasonSuitability: "חורף, אביב, וגם נעים בקיץ בצל.",
        timeSuitability: ["צהריים", "אחה\"צ"],
        mapsLink: "https://goo.gl/maps/c6jV7vN3K8M2wK1v8",
        infoLink: "https://www.kkl.org.il/forestsearch/martyrs_forest.aspx"
    },
    {
        id: "trip_18",
        name: "טיילת החומות בירושלים",
        shortDescription: "תצפית היסטורית ורומנטית מגובה החומות של העיר העתיקה.",
        region: "ירושלים והסביבה",
        routeType: "קווי",
        lengthCategory: "ארוך",
        durationText: "כשעתיים",
        durationCategory: "חצי יום",
        difficulty: "בינוני",
        style: ["נוף", "רומנטי", "שקיעה"],
        hasFoodOption: true,
        elevationDetail: "המון מדרגות עליה וירידה לאורך החומות. מצריך כושר קל.",
        driveDistance: "העיר העתיקה, ירושלים.",
        startPoint: "שער יפו",
        endPoint: "שער האשפות (הטיילת הדרומית)",
        highlights: ["תצפיות פנורמיות לעיר העתיקה והחדשה", "בריזה ירושלמית", "הליכה בתוואי היסטורי"],
        foodRecommendations: "סיימו בשוק מחנה יהודה הסמוך לארוחת ערב ססגונית.",
        whatToBring: "מים, כובע (חשוף לשמש) ונעלי הליכה.",
        seasonSuitability: "סתיו, חורף, אביב. (בקיץ חם מדי ביום).",
        timeSuitability: ["אחה\"צ", "שקיעה"],
        mapsLink: "https://goo.gl/maps/c6jV7vN3K8M2wK1v9",
        infoLink: "https://www.pami.co.il/"
    },

    // --- דרום ---
    {
        id: "trip_19",
        name: "עין עבדת",
        shortDescription: "נווה מדבר קסום, קניון גיר לבן עמוק ומפל מים מפתיע בלב המדבר.",
        region: "דרום",
        routeType: "קווי",
        lengthCategory: "ארוך",
        durationText: "כ-2.5 שעות",
        durationCategory: "חצי יום",
        difficulty: "קל",
        style: ["טבע", "מים", "נוף"],
        hasFoodOption: true,
        elevationDetail: "הליכה שטוחה אל המפל, ויש אפשרות לעלות במדרגות סלע גבוהות לחלק העליון.",
        driveDistance: "ליד מדרשת בן גוריון (שדה בוקר).",
        startPoint: "קופות עין עבדת (הכניסה התחתונה)",
        endPoint: "חניון עין עבדת עליון",
        highlights: ["מפל המים והבריכה (אסור להיכנס)", "יעלים שמסתובבים חופשי", "קניון מרשים"],
        foodRecommendations: "אכלו בחוות רוטה או בפונדק שדה בוקר.",
        whatToBring: "מים (חובה), כובע.",
        seasonSuitability: "חורף, סתיו, אביב. (סגור בימי שטפונות).",
        timeSuitability: ["בוקר"],
        mapsLink: "https://goo.gl/maps/c6jV7vN3K8M2wK1v0",
        infoLink: "https://www.parks.org.il/reserve-park/ein-avdat/"
    },
    {
        id: "trip_20",
        name: "מצפה רמון - טיילת המכתש והר גמל",
        shortDescription: "הליכה רומנטית על שפת המכתש, מומלץ במיוחד בשעת השקיעה.",
        region: "דרום",
        routeType: "קצר",
        lengthCategory: "קצר",
        durationText: "כשעה-שעתיים",
        durationCategory: "2-3 שעות",
        difficulty: "קל",
        style: ["נוף", "רומנטי", "שקיעה"],
        hasFoodOption: true,
        elevationDetail: "טיילת מוסדרת ברובה, עלייה קצרה להר גמל.",
        driveDistance: "מצפה רמון.",
        startPoint: "מרכז מבקרים מצפה רמון",
        endPoint: "תצפית הר גמל",
        highlights: ["נוף מרהיב ועוצמתי של מכתש רמון", "שקיעות מהיפות בישראל", "פסלים ותצפיות"],
        foodRecommendations: "ברובע דרכי הבשמים יש מאפיות מצוינות ופאבים מקומיים.",
        whatToBring: "לבוש חם! במצפה רמון תמיד קריר בערב.",
        seasonSuitability: "כל השנה. קר מאוד בחורף.",
        timeSuitability: ["שקיעה"],
        mapsLink: "https://goo.gl/maps/c6jV7vN3K8M2wK1v1",
        infoLink: "https://www.parks.org.il/reserve-park/ramon/"
    },
    {
        id: "trip_21",
        name: "החולות הצבעוניים במכתש הגדול",
        shortDescription: "חוויה ילדותית-כיפית לזוגות, איסוף חול צבעוני בבקבוקים בלב הנוף המדברי.",
        region: "דרום",
        routeType: "קצר",
        lengthCategory: "קצר",
        durationText: "כחצי שעה - שעה",
        durationCategory: "2-3 שעות",
        difficulty: "קל",
        style: ["טבע", "נוף", "רומנטי"],
        hasFoodOption: false,
        elevationDetail: "הגעה ישירה עם הרכב עד לאתר, ללא מאמץ פיזי.",
        driveDistance: "קרוב לירוחם.",
        startPoint: "החולות הצבעוניים (המכתש הגדול)",
        endPoint: "החולות הצבעוניים",
        highlights: ["שכבות של חולות במגוון צבעים", "נוף מכתש פתוח", "שקט מדברי"],
        foodRecommendations: "קחו אתכם ערכת קפה ועוגיות, או סעו לירוחם לאכול.",
        whatToBring: "בקבוק זכוכית קטן (למלא בחול!), מים, כובע.",
        seasonSuitability: "סתיו, חורף ואביב.",
        timeSuitability: ["בוקר", "אחה\"צ"],
        mapsLink: "https://goo.gl/maps/c6jV7vN3K8M2wK1v2",
        infoLink: "https://he.wikipedia.org/wiki/החולות_הצבעוניים"
    },
    {
        id: "trip_22",
        name: "גבעת הכלניות (קבר פולה ודוד בן גוריון)",
        shortDescription: "תצפית יפהפייה אל נחל צין מנקודת פסטורלית ובעלת משמעות היסטורית.",
        region: "דרום",
        routeType: "מעגלי",
        lengthCategory: "קצר",
        durationText: "חצי שעה - שעה",
        durationCategory: "2-3 שעות",
        difficulty: "קל",
        style: ["נוף", "רומנטי", "טבע"],
        hasFoodOption: true,
        elevationDetail: "הליכה קצרה וקלילה מהחניה.",
        driveDistance: "מדרשת בן גוריון.",
        startPoint: "אחוזת קבר בן גוריון",
        endPoint: "אחוזת קבר בן גוריון",
        highlights: ["תצפית עוצרת נשימה לנחל צין ורמת עבדת", "גן מטופח וירוק במדבר", "יעלים מקומיים"],
        foodRecommendations: "שפע אפשרויות במדרשה עצמה, כולל פאב מקומי ופיצריה.",
        whatToBring: "מצלמה, משקפי שמש.",
        seasonSuitability: "כל השנה. יפה במיוחד כשיש פריחה בחורף.",
        timeSuitability: ["בוקר", "שקיעה"],
        mapsLink: "https://goo.gl/maps/c6jV7vN3K8M2wK1v3",
        infoLink: "https://www.parks.org.il/reserve-park/ben-gurions-tomb-national-park/"
    },
    {
        id: "trip_23",
        name: "פארק תמנע (עמודי שלמה)",
        shortDescription: "ביקור בפארק מדברי ענק עם תצורות סלע מרהיבות, אגם מלאכותי והיסטוריה.",
        region: "דרום",
        routeType: "מעגלי",
        lengthCategory: "ארוך",
        durationText: "חצי יום עד יום שלם (נסיעה בין התחנות)",
        durationCategory: "יום מלא",
        difficulty: "קל",
        style: ["טבע", "נוף", "מים"],
        hasFoodOption: true,
        elevationDetail: "ניתן לעשות מסלולים רגליים קצרים בכל תחנה, עליות מתונות.",
        driveDistance: "כ-25 דקות מצפון לאילת.",
        startPoint: "הכניסה לפארק תמנע",
        endPoint: "אגם תמנע",
        highlights: ["הפטרייה", "עמודי שלמה", "שייט פדלים באגם"],
        foodRecommendations: "מסעדת חאן המלך שלמה בפארק (ליד האגם) או ארוחה באילת.",
        whatToBring: "מים רבים, כובע, קרם הגנה.",
        seasonSuitability: "חורף וסתיו. (חם מאוד בקיץ!).",
        timeSuitability: ["בוקר", "אחה\"צ"],
        mapsLink: "https://goo.gl/maps/c6jV7vN3K8M2wK1v4",
        infoLink: "https://www.parktimna.co.il/"
    },
    {
        id: "trip_24",
        name: "נחל פרצים ומערת הקמח",
        shortDescription: "מסלול הליכה (או אופניים) בתוך ערוץ לבן מחוואר, באווירה מדברית שקטה.",
        region: "דרום",
        routeType: "קווי",
        lengthCategory: "ארוך",
        durationText: "2-3 שעות",
        durationCategory: "חצי יום",
        difficulty: "בינוני",
        style: ["טבע", "נוף"],
        hasFoodOption: false,
        elevationDetail: "הליכה בתוך הערוץ, מישורי ברובו.",
        driveDistance: "דרום ים המלח / צומת נווה זוהר.",
        startPoint: "חניון לילה מישור עמיעז",
        endPoint: "מערת הקמח (בדיקה אם פתוחה, כרגע לעיתים סגורה)",
        highlights: ["קירות חוואר לבנים ומרשימים", "מסלול מושלם בליל ירח מלא", "שקט מוחלט"],
        foodRecommendations: "מומלץ להביא אוכל מהבית, המסעדות הקרובות נמצאות במתחם המלונות עין בוקק.",
        whatToBring: "הרבה ממים, פנס ראש (אם הולכים בלילה/מערה).",
        seasonSuitability: "חורף ואביב, או לילות ירח מלא בקיץ.",
        timeSuitability: ["בוקר", "ערב (ירח מלא)"],
        mapsLink: "https://goo.gl/maps/c6jV7vN3K8M2wK1v5",
        infoLink: "https://www.parks.org.il/"
    }
];